---
- name: Kubernetes Cluster Troubleshooting
  hosts: master
  become: yes
  tasks:
    - name: Check system status
      shell: |
        echo "=== System Information ==="
        uname -a
        echo ""
        echo "=== Memory Usage ==="
        free -h
        echo ""
        echo "=== Disk Usage ==="
        df -h
        echo ""
        echo "=== Network Interfaces ==="
        ip addr show
        echo ""
        echo "=== DNS Configuration ==="
        cat /etc/resolv.conf
        echo ""
        echo "=== SystemD Resolved Status ==="
        systemctl status systemd-resolved --no-pager
      register: system_info
      ignore_errors: yes

    - name: Display system information
      debug:
        var: system_info.stdout_lines

    - name: Check Kubernetes components
      shell: |
        echo "=== Kubelet Status ==="
        systemctl status kubelet --no-pager
        echo ""
        echo "=== Containerd Status ==="
        systemctl status containerd --no-pager
        echo ""
        echo "=== Kubernetes Version ==="
        kubectl version --client
        echo ""
        echo "=== Cluster Info ==="
        kubectl cluster-info
        echo ""
        echo "=== Node Status ==="
        kubectl get nodes -o wide
        echo ""
        echo "=== All Namespaces ==="
        kubectl get namespaces
        echo ""
        echo "=== All Pods ==="
        kubectl get pods --all-namespaces -o wide
        echo ""
        echo "=== Services ==="
        kubectl get services --all-namespaces
      environment:
        KUBECONFIG: /home/azureuser/.kube/config
      register: k8s_info
      ignore_errors: yes

    - name: Display Kubernetes information
      debug:
        var: k8s_info.stdout_lines

    - name: Check network and DNS
      shell: |
        echo "=== CoreDNS Status ==="
        kubectl get pods -n kube-system -l k8s-app=kube-dns -o wide
        echo ""
        echo "=== CoreDNS ConfigMap ==="
        kubectl get configmap coredns -n kube-system -o yaml
        echo ""
        echo "=== Calico Status ==="
        kubectl get pods -n kube-system -l k8s-app=calico-node -o wide
        echo ""
        echo "=== Network Test ==="
        kubectl run network-test --image=busybox:1.28 --rm -it --restart=Never --command -- ping -c 3 8.8.8.8 || true
        echo ""
        echo "=== DNS Test ==="
        kubectl run dns-test --image=busybox:1.28 --rm -it --restart=Never --command -- nslookup kubernetes.default || true
      environment:
        KUBECONFIG: /home/azureuser/.kube/config
      register: network_info
      ignore_errors: yes

    - name: Display network information
      debug:
        var: network_info.stdout_lines

    - name: Check for common errors
      shell: |
        echo "=== Recent System Errors ==="
        journalctl --since "10 minutes ago" --priority=err --no-pager | tail -20
        echo ""
        echo "=== Kubelet Logs ==="
        journalctl -u kubelet --since "10 minutes ago" --no-pager | tail -20
        echo ""
        echo "=== Containerd Logs ==="
        journalctl -u containerd --since "10 minutes ago" --no-pager | tail -20
      register: error_logs
      ignore_errors: yes

    - name: Display error logs
      debug:
        var: error_logs.stdout_lines