jenkins:
  systemMessage: "Jenkins CI/CD Server - Custom DNS Configuration"
  numExecutors: 2
  mode: NORMAL
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin123"
          
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  remotingSecurity:
    enabled: true

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"