apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-api-ingress
  namespace: python-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.daedalusproject.online
      secretName: python-api-tls
  rules:
    - host: api.daedalusproject.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-rest-api
                port:
                  number: 8000